ignore upload-artifact if CHARM_FILE is unset or unknown
canonical/operator-workflows pull request #249
Opened 2024-02-05 20:20 UTC by addyess

### Overview

Do not upload the working directory as an artifact named `UNKNOWN-charm`

### Rationale

In cases where `env.CHARM_FILE` is unset (ie -- when CHARM_NAME is "UNKNOWN" because there is no charmcraft.yaml or metadata.yaml in the provided working-directory, the `CHARM_FILE` env file is unset because the `Pack charm` step will be skipped.  In this event, skip uploading the artifact. 

### Workflow Changes

the build-charm step of `integration_test` will be adjusted to have an empty `charm-file`
This can be valuable for repos that wish to test a bundle or a repo that wishes to test multiple charms within the same repo

### Checklist

- [x ] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [ ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

2024-02-05 20:22 UTC, addyess commented
@arturo-seijas Here's another situation i encountered when i have multiple charms in the same repo.  I'm building the charms independently, but this part of the workflow comes along and overwrites the `UNKNOWN-charm` artifact.  Very likely this is unintended

2024-02-06 10:26 UTC, arturo-seijas approved these changes
Thank you!

2024-02-06 12:27 UTC, merkata approved these changes, later dismissed

2024-02-06 15:12 UTC, arturo-seijas requested changes
It looks like there's a [syntax error](https://github.com/canonical/operator-workflows/actions/runs/7801833101). Can you double check @addyess ?

2024-02-06 15:30 UTC, arturo-seijas approved these changes

2024-02-06 16:37 UTC, cbartz approved these changes

2024-02-06 16:44 UTC, merged