Set  integration test timeout
canonical/operator-workflows pull request #267
Opened 2024-03-26 07:34 UTC by louiseschmidtgen

## Description
I would like to add a timeout to the integration test. It is not possible to set it on our side (k8s-operator) and has to be set in the actual integration test job. I propose a timeout of 120 minutes.

The reason for the request is an integration test running for 6 hours and not being able to cancel the workflow: https://github.com/canonical/k8s-operator/actions/runs/8418728595/job/23049966931

2024-03-26 09:14 UTC, yanksyoon commented
/canonical/self-hosted-runners/run-workflows c15ce86733ae8ebf69a3e1861f23b3408937f7ad

2024-03-26 13:02 UTC, addyess requested changes
Maybe make a test-timeout input?

2024-03-26 13:02 UTC, addyess commented on .github/workflows/integration_test_run.yaml
> +    timeout-minutes: 120
any chance you could make this an input called "test-timeout" or some such?

2024-03-26 13:15 UTC, addyess commented
@arturo-seijas and @cbartz, Do you think this is a good addition to the integration tests.  We found some rouge tests running after 5 hours because of failed test tear down.  The default gh run is 6 hours if the timeout isn't specified

2024-03-26 13:43 UTC, jdkandersson submitted a review, later dismissed

2024-03-26 13:43 UTC, jdkandersson commented on .github/workflows/integration_test_run.yaml
Oh I forgot to mention, please document this input option in the readme 🙂

2024-03-26 14:38 UTC, louiseschmidtgen commented on .github/workflows/integration_test_run.yaml
I will add it now thanks!

2024-03-26 15:06 UTC, cbartz commented
/canonical/self-hosted-runners/run-workflows f7fb90ed93d1fec5b3f56a7acd088a39e56f6fa5

2024-03-26 15:06 UTC, cbartz approved these changes

2024-03-26 19:51 UTC, addyess commented
@jdkandersson do we have your +1?

2024-03-27 04:19 UTC, jdkandersson approved these changes

2024-03-27 04:20 UTC, jdkandersson commented
I think we'll just need someone to help you pass the tests, perhaps @yanksyoon?

2024-03-27 07:36 UTC, yanksyoon commented
@jdkandersson This looks good to me, would you be able to merge this until we have a fix for the forked artifact uploads please?

2024-03-27 07:50 UTC, merged