Add module to the matrix
canonical/operator-workflows pull request #50
Opened 2022-11-28 02:22 UTC by jdkandersson

Adds an additional parameter `modules` so that, if the integration tests have multiple modules, they can be run in parallel. Note that currently, any integration tests in multiple modules that require charms with the same name will fail because the `model` fixture from pytest operator is module scoped and we use the fixed model `testing` which means that any attempts to redeploy a charm in another module will have failures. This parameter also speeds up test execution.

2022-11-28 02:31 UTC, weiiwang01 submitted a review, later dismissed

2022-11-28 05:08 UTC, yhaliaw approved these changes, later dismissed

2022-11-28 08:18 UTC, merkata approved these changes, later dismissed
Nice!

2022-11-28 08:19 UTC, arturo-seijas requested changes
You'll want to add the new parameter also to https://github.com/canonical/operator-workflows/blob/main/.github/workflows/test_and_publish_charm.yaml

2022-11-29 06:35 UTC, weiiwang01 approved these changes

2022-11-29 08:36 UTC, gregory-schiano approved these changes
LGTM

2022-11-29 09:24 UTC, arturo-seijas approved these changes
LGTM

2022-11-29 12:27 UTC, merkata approved these changes

2022-11-30 00:16 UTC, merged